services:
  - type: web
    name: spock-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerTarget: web
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: "8000"
      - fromGroup: spock-env
